# Generated by Django 4.2.1 on 2023-05-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_first_lastname_customers_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(blank=True, max_length=15, null=True)),
                ('adress', models.CharField(blank=True, max_length=13, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=14, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
