# Generated by Django 4.2.1 on 2023-05-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customers_age_alter_customers_mobile_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(blank=True, max_length=15, null=True)),
                ('addharmobile_no', models.IntegerField(blank=True, null=True)),
                ('Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
