# Generated by Django 4.2.1 on 2023-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customeraddhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_Adresses', to='customer.customers'),
        ),
    ]
